services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuaSenhaSuperSegura123!
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
  api:
    image: secretariaapi
    build: .
    ports: 
      - "8080:8080"
    environment: 
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=SecretariaDB;User Id=sa;Password=SuaSenhaSuperSegura123!;Encrypt=False;

volumes:
  sqlserver_data: